#! /bin/sh

WIDTH=200
HEIGHT=200
DATEFMT="+%m/%d %a %I:%M:%S%p"
SHORTFMT="+%H:%M:%S"

case "$BLOCK_BUTTON" in
  1|2|3) 
	unset x y w h
  	eval $(xwininfo -id $(xdotool getactivewindow) |
    	sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
           -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
           -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
           -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )

	# the position of the upper left corner of the popup
	posX=$(($x+$w-$WIDTH-10))
	posY=$(($y+$h-$HEIGHT+5))
	i3-msg -q "exec yad --calendar \
        --width=$WIDTH --height=$HEIGHT \
	    --undecorated --fixed \
	    --close-on-unfocus --no-buttons \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac
echo "$LABEL$(date "$DATEFMT")"
echo "$LABEL$(date "$SHORTFMT")"
