#!/usr/bin/env bash

# Copyright 2016 Patrick Haun
# Edited: Denis Kadyshev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#SINK=$( pacmd list-sinks | awk '/index:/{i++} /* index:/{print i; exit}' )
#NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

SINK=$(pacmd stat | awk -F": " '/^Default sink name: /{print $2}')
NOW=$(pacmd list-sinks | awk '/^\s+name: /{indefault = $2 == "<'$SINK'>"}/^\s+volume: / && indefault {print $5; exit}' | awk -F"%" '{print $1}')

echo "$NOW%"
